use_frameworks!

target 'HUD_Example' do
  pod 'HUD', :path => '../'
  pod 'MBProgressHUD', '~> 1.1.0'

  target 'HUD_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
